#server port setting
server:
   port: 8001
eureka:
   client:
      register-with-eureka: false
      fetch-registry: false
      serviceUrl:
         defaultZone: http://192.168.1.20:8001/eureka/
spring:
   application:
      name: rrtf-eureka-server