spring:
#datasource setting
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tuofu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
#jpa setting
   jpa:
      properties:
         hibernate:
            hbm2ddl:
               auto: update
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      database: mysql
      show-sql: true
      format_sql: true
      hibernate:
         ddl-auto: update
         naming:
            strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
#thymeleaf setting
   thymeleaf:
      prefix: classpath:static/tuofu/
      suffix: .html
      mode: LEGACYHTML5
      encoding: UTF-8
      content-type: text/html
      cache: false
#file upload setting
   http:
      multipart:
         enabled: true
         file-size-threshold: 0
         max-file-size: 5MB
         max-request-size: 10MB
#upload.location setting
upload:
   location: \static\tuoFu\img